server:
  port: 8084
  servlet:
    context-path: /ad-search

spring:
  application:
    name: ad-search
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ad?serverTimezone=Asia/Shanghai
    username: root
    password: root


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

feign:
  hystrix:
    enabled:true